### ISSUE TITLE
Move editor unable to edit moves with 2nd animations

### ISSUE THREAD

**Issue by QuestionableSpecimen** [hzla/Pokeweb-Live#1]
Whenever I try to edit a move like Brick Break or Solar Beam, for some reason it results in an animation that only has the first animation reguardless of which part of the move you are in. For example in solar beam, if I upload the txt file via pokeweb (even if there's no change to the move what so ever), it would result in solar beam having the charging animation for both the charging portion and the attacking portion. 

I've posted 2 text files. 
The first one is what brick break's move animation script usually looks like when you click Download Anim Script. 
[brick_break_move_script.txt](https://github.com/user-attachments/files/16971003/brick_break_move_script.txt)

The 2nd one is when I upload the first one and then downloaded it again. For some reason, this results in a txt file that just repeats the non-screen break animation twice
[brick_break_uploaded.txt](https://github.com/user-attachments/files/16971004/brick_break_uploaded.txt)

**Comment by DaSquyd** [comment]
Done: #2
